const entries=[
  {name:"Jikan",description:"Unofficial, read-only MyAnimeList data API for anime and manga.",category:"Anime",type:"REST",auth:"None",pricing:"Free",https:true,cors:"Yes",docs:"https://docs.api.jikan.moe/",base_url:"https://api.jikan.moe/v4",website:"https://jikan.moe/",github:"https://github.com/jikan-me/jikan-rest",license:"MIT",tags:["anime","manga","unofficial","free"],unofficial:true,officiality:"unofficial"},
  {name:"AniList GraphQL API",description:"GraphQL API for anime and manga metadata, characters, staff, studios, and lists.",category:"Anime",type:"GraphQL",auth:"None",pricing:"Free",https:true,cors:"Yes",docs:"https://docs.anilist.co/",base_url:"https://graphql.anilist.co",website:"https://anilist.co/",license:"See AniList terms",tags:["anime","manga","graphql","free"]},
  {name:"Spotify Web API",description:"Metadata and playback-control API for Spotify artists, albums, tracks, playlists, and user libraries.",category:"Music",type:"REST",auth:"OAuth",pricing:"Free",https:true,cors:"Yes",docs:"https://developer.spotify.com/documentation/web-api",base_url:"https://api.spotify.com/v1",website:"https://developer.spotify.com/",license:"Spotify Developer Terms",tags:["spotify","music","streaming","oauth","free tier"]},
  {name:"Last.fm API",description:"Music metadata, charts, artists, albums, tracks, tags, and listening history API.",category:"Music",type:"REST",auth:"API Key",pricing:"Free",https:true,cors:"Yes",docs:"https://www.last.fm/api",base_url:"https://ws.audioscrobbler.com/2.0/",website:"https://www.last.fm/",license:"Last.fm API Terms",tags:["music","scrobble","metadata","free"]},
  {name:"The Movie Database API",description:"Movie, TV, actor, image, genre, and watch-provider metadata for non-commercial projects with attribution.",category:"Movies & TV",type:"REST",auth:"API Key",pricing:"Free",https:true,cors:"Yes",docs:"https://developer.themoviedb.org/docs/getting-started",base_url:"https://api.themoviedb.org/3",website:"https://www.themoviedb.org/",license:"TMDB API Terms",tags:["movies","tv","streaming","netflix","free for non-commercial"]},
  {name:"TVmaze API",description:"Free TV data API for shows, episodes, schedules, cast, people, images, and search.",category:"Movies & TV",type:"REST",auth:"None",pricing:"Free",https:true,cors:"Yes",docs:"https://www.tvmaze.com/api",base_url:"https://api.tvmaze.com",website:"https://www.tvmaze.com/",license:"CC BY-SA",tags:["tv","shows","episodes","streaming","free"]},
  {name:"Netflix catalog metadata — unofficial",description:"Community/unofficial Netflix catalog tooling for metadata experiments. Netflix does not publish an official public developer API; verify project availability and terms before use.",category:"Movies & TV",type:"REST",auth:"Unknown",pricing:"Free",https:true,cors:"Unknown",docs:"https://github.com/Xaverick/NetflixAPI",base_url:"https://github.com/Xaverick/NetflixAPI",website:"https://www.netflix.com/",license:"See project and Netflix terms",tags:["netflix","streaming","unofficial","community"],unofficial:true,officiality:"unofficial"}
];
export async function fetchSource(){return entries.map(x=>({...x,source_url:"https://github.com/LegendXD221/ApiVanta/blob/master/scripts/sources/featured-free.mjs"}));}
